# Generated by Django 3.2.15 on 2022-08-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20220823_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[('NEW', 'Необработанный'), ('CON', 'Обработанный'), ('CCD', 'Отмененный'), ('FF', 'Исполненный')], db_index=True, default='NEW', verbose_name='Статус заказа'),
        ),
    ]
