# Generated by Django 3.2.15 on 2022-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('CON', 'Обработанный'), ('CCD', 'Отмененный'), ('FF', 'Исполненный')], default='NEW', max_length=3, verbose_name='Статус заказа'),
        ),
    ]
